### ISSUE TITLE
Transcribe AOSTASK (pp. 630-634)

### ISSUE THREAD

**Issue by thewonderidiot** [rburkey2005/virtualagc#100]
Transcribe the scans for the AOSTASK log section into [its source file](https://github.com/rburkey2005/virtualagc/blob/master/Aurora12/AOSTASK.agc). This section ranges from pages 630 to 634.

This section does not appear to have a corresponding section in Luminary 099, despite partially sharing a name with [AOSTASK AND AOSJOB](https://github.com/rburkey2005/virtualagc/blob/master/Luminary099/AOSTASK_AND_AOSJOB.agc). It will need to be written from scratch.

Reduced quality scans can be found [here](http://www.ibiblio.org/apollo/ScansForConversion/Aurora12/). The original quality scans are available at [the Internet Archive page for Aurora](https://archive.org/details/aurora00dapg). Note that in both cases, the page numbers specified on this ticket are those printed on the original pages, *not* those in the filenames. The numbers will be close, though, so you should be able to find them pretty quickly. The start of the log section should be fairly obvious.

**Comment by ohommes** [comment]
Transcribed AOSTASK and ready for review/verification
