### ISSUE TITLE
Confusion over address spaces in yaAGC command-line debugger.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rburkey2005/virtualagc#13]
```
Here are several related issues having to do with command-line debugging
and the different address spaces of the AGC CPU.  I'm not sure if they're
bugs so much as confusing points.

1.  It's not obvious how to select which address space is being used in
(for example) an 'x' command.  The help system does not describe how to
select different address spaces, as far as I can tell.

2.  The output of the 'x' command shows different data when I use addresses
which (in my mind) *may* be in different address spaces, but the addresses
it prints are always the same.

3.  Is there some way to use addresses as opposed to symbols with the
'print' command?

```

Original issue reported on code.google.com by `rburkey2...@gmail.com` on 5 Apr 2009 at 3:04

**Comment by ohommes** [comment]
Started working on all the help information. I noticed help was only working for classes of commands. I will fix this in the next few days.

**Comment by ohommes** [comment]
Updated help for print, x and set to show how to use all the possible address usages.
Examples:
  print MPAC
  print &MPAC
  print *0x6c
  print *0154
  print *E0,1554

  x/1 E0,1554
  x/1 0154
  x/1 0x6c
  x/1 &MPAC

  set MPAC=9
  set *0x6c=8
  set *0154=7
  set *E0,1554=6
