### ISSUE TITLE
Add ALGA alarms to yaAGC

### ISSUE THREAD

**Issue by thewonderidiot** [rburkey2005/virtualagc#137]
We've decided to add in the Night Watchman alarm, which goes off if the software goes for too long without reading from address 67 (NEWJOB). That's only one of the ALGA alarms, all of which trigger restarts through the same mechanism. The other ALGA alarms are:

- Parity Alarm -- All fixed and erasable reads must have the correct parity.
- Rupt Lock -- An interrupt of any type must happen frequently enough, but the computer can't spend too long servicing rupts. This one I have seen, and Validation would need to be changed to enable interrupts.
- TC Trap -- The TC or TCF instructions must be executed frequently enough, but the computer can't spend too long executing only TCs and TCFs.

We probably want to leave the parity alarm out of yaAGC, since its presence doesn't add anything other than binary compatibility to the hardware. Nothing's ever going to end up with incorrect parity in an emulator.

The others are probably worth adding at some point, especially if Aurora's going to want to trigger some of them. For the time being, though, just the Night Watchman should be enough to prevent most lockups.

**Comment by rburkey2005** [comment]
The yaAGC doesn't support parity anyway.


Sent on my Virgin Mobile Samsung Galaxy S® 5

-------- Original message --------

**Comment by thewonderidiot** [comment]
Yeah, that's what I was trying to say in not enough words. We'd have to add parity support to yaAGC for the parity alarm to be happy, but there's little point in doing so because there's then no way for it to become unhappy. And it would break backwards compatibility for all existing binaries.

**Comment by thewonderidiot** [comment]
As part of this, I think I'll add the capability of the CH77 Restart Monitor too, so we can take a look at that channel to see when any of these alarms happen, and which.

**Comment by rburkey2005** [comment]
Sure, why not?


Sent on my Virgin Mobile Samsung Galaxy S® 5

-------- Original message --------

**Comment by thewonderidiot** [comment]
So, according to R-700v3 the behavior of the Night Watchman is:
"Occurs if computer software should fail to access address 67 at least once every 0.64 second."

The actual behavior, looking at the circuit, is roughly in line with this, but slightly different. More precisely, that should read:
"Occurs if address 67 is not read at least once within every other 0.64 second window".

 In other words, the timing pays no attention to exactly _when_ in the window the read occurs, and it's possible for the alarm to take up to 1.28s to trigger, if the last read was placed right in the beginning of the 0.64 second window that's not checked.

**Comment by thewonderidiot** [comment]
With alarms in, I'm going to accelerate merging in my hardware-related yaDSKY changes. What actually triggers the RESTART light on the DSKY is execution of any hardware-generated GOJAM sequences. Those are happening more than just at the start, now, so the DSKY should light that indicator accordingly when a restart is taken.

**Comment by indy91** [comment]
Something isn't quite right. When I try to use Program 63 in my Luminary099 PDI testing scenario, I get a 210 program alarm and the flashing verb 37 that wants me to change program. I haven't checked yet which of the pull requests causes it. This is just an amateur guess, but maybe one of the new flags from the latest commit has to be initialized? This problem might very well have to do with the NASSP implementation though.

**Comment by thewonderidiot** [comment]
Figures. You're right, I do need to initialize all the new flags in agc_engine_init. However, if they start in the wrong state, it'll sort itself out very quickly at boot time, and be correct after that. Can you check the state of channel 77 after this happens, to see if one of the alarms is marked as tripped?

**Comment by indy91** [comment]
Channel 77 is all zeros before and after the 210 alarm. If you literally mean channel 77 in octal, accessed with V11N10E 77E.

Also, I think adding new flags might be a challenge for saving/loading in NASSP. The struct for saving AGC flags says "struct is full". Whatever that means. :D And I haven't done anything in this part of the code, so I don't feel very comfortable changing it.

**Comment by thewonderidiot** [comment]
Grrr, okay, I'll dig into it tonight. It should be fairly easy to trigger, right? Just try to start P63 in one of the scenarios you've posted? I can also take a look at the NASSP save/loading stuff to see if I can figure out what they mean by that.

**Comment by indy91** [comment]
You might be in luck, the 210 alarm also happens when I revert both commits. I've only done Aurora12 and CSM stuff in the last few days so maybe I changed something for the worse in the mean time.

**Comment by indy91** [comment]
I had added the logic to choose the appropiate LGC binary based on mission number. Aurora12 as the default binary for Apollo mission numbers 0 and smaller, Luminary for Apollo 11 and earlier and so on. An harmless change I thought, it works the same way for the CMC already. But apparently that broke something with the IMU. Sorry for the false alarm!

**Comment by thewonderidiot** [comment]
Aha! Excellent, no worries. :) I was really befuddled at how none of the CH77 bits were set if the alarms were at fault. Especially since IIRC Apollo 11 flew without the CH77 alarm boxes installed, so Luminary099 shouldn't know how to clear it automatically.
