### ISSUE TITLE
MS Vista Failed to install Virtual AGC

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rburkey2005/virtualagc#24]
```
What steps will reproduce the problem?

1. Download file VirtualAGC-setup.exe
2. Run VirtualAGC-setup.exe
 

What is the expected output? What do you see instead?
Please find attached image.

What version of the product are you using? On what operating system?
The latest, I'm hope. Operation system: Windows Vista

Please provide any additional information below.


```

Original issue reported on code.google.com by `michael....@gmail.com` on 7 Aug 2009 at 4:04

Attachments:
* [Setup.png](https://storage.googleapis.com/google-code-attachments/virtualagc/issue-24/comment-0/Setup.png)

**Comment by rburkey2005** [comment]
I guess since nobody has seen this in 7 years, we can assume it's not a problem, closing it out.
