### ISSUE TITLE
Bug in yaYUL --html

### ISSUE THREAD

**Issue by rburkey2005** [rburkey2005/virtualagc#45]
In the colorized syntax-highlighted HTML produced for AGC assembly listings by using the "--html" switch in yaYUL, the decorative HTML headers optionally added to these files sometimes causes assembly itself to fail.  Out of all the existing AGC source files, this occurs in exactly four cases:  the AGC source files

- Luminary099/LUNAR_LANDING_GUIDANCE_EQUATIONS.agc

- Luminary099/KALCMANU_STEERING.agc

- Luminary131/LUNAR_LANDING_GUIDANCE_EQUATIONS.agc

- Luminary131/KALCMANU_STEERING.agc

In these four cases, the initial lines of the files, which add the decoration, namely

   ### FILE="Main.annotation"

must be removed, or else assembly fails.  The lines have been removed at present, but the problem should be fixed, and I'm at a complete loss as to why it's happening.

**Comment by thewonderidiot** [comment]
The problem appears to be happening because in Pass.c, inclusion of an HTML line destroys knowledge of the current program counter. And apparently these four log sections are the only ones in the entire set of sources we have so far that don't start with enough pseudo-ops to reconstruct (or change) what the program counter should be.

Changing
 ```C
if (HtmlCheck(WriteOutput, InputFile, s, sizeof(s), CurrentFilename, &CurrentLineAll, &CurrentLineInFile)) {
    continue;
}
```

to

 ```C
if (HtmlCheck(WriteOutput, InputFile, s, sizeof(s), CurrentFilename, &CurrentLineAll, &CurrentLineInFile)) {
    ParseOutputRecord.ProgramCounter = ParseInputRecord.ProgramCounter;
    ParseOutputRecord.EBank = ParseInputRecord.EBank;
    ParseOutputRecord.SBank = ParseInputRecord.SBank;
    continue;
}
```

fixes the problem. The second two lines aren't necessary but are probably not bad practice to bring along anyways.

**Comment by rburkey2005** [comment]
Super! And stupid of me to allow it in the first place. Do you want to fix it, or shall I?


Sent on my Virgin Mobile Samsung Galaxy S® 5

-------- Original message --------

**Comment by thewonderidiot** [comment]
Would you mind doing it? I had the bandwidth to download just a snapshot of master for testing, but doing a full git clone so I can commit the changes seems to be beyond my internet's current capabilities.

**Comment by rburkey2005** [comment]
Certainly.  I forgot you were off in the boonies right now, 
connectivity-wise.

**Comment by rburkey2005** [comment]
Implemented Mike's change.  Worked great!
