### ISSUE TITLE
Possible incorrect TIME6 behavior.

### ISSUE THREAD

**Issue by eddievhfan1984** [rburkey2005/virtualagc#46]
This is related to NASSP for Orbiter.

We've been testing LM powered descent operations, and have been getting consistent 1103 alarms (unused CCS branch, causing a P00DOO) during DAP usage. The V05N08 display pinpoints the problematic CCS in the T6RUPT handler routines (fixed bank 017, address 02032), and comparing the AGC assembly listing information with the C code for handling timers, it seems possible to me that the TIME6 counter is improperly handled.

According to code comments for the Luminary 99 assembly code (page 1403), it stipulates that TIME6 should at all times be greater than +0, triggering the interrupt after it is loaded with -0, 67777 indicating counter disabled. Otherwise, the CCS instruction transfers control to the abort handler, causing the 1103.
![screenshot 79](https://cloud.githubusercontent.com/assets/13581189/18068767/10e7bd9c-6e11-11e6-8220-e8d088191b7a.png)
![screenshot 80](https://cloud.githubusercontent.com/assets/13581189/18068771/14702832-6e11-11e6-94b4-41366769ac30.png)

EDIT: I originally thought it was based on an increasing counter/PINC, but I did not know about the 1+(-1)=-0 detail of the adder. Thanks to thewonderidiot for clearing that up.

**Comment by thewonderidiot** [comment]
So it looks like there's a couple compounding problems here. First, going off the schematics, T6RUPT is triggered by ZOUT, whereas in the yaAGC code it looks like that is not the case. Second, in the AGC adder, 1 + (-1) = -0. So the TIME6 sequence would be 3,2,1,-0. yaAGC currently counts from 1 down to +0.

Not sure if that covers everything. I'll be able to do a more detailed analysis in a couple of days.

**Comment by thewonderidiot** [comment]
By the way, isn't the negative branch of that CCS effectively a TC to self? Would't that cause an infinite loop and subsequent TC trap? I guess they must have considered the negative case bad enough to force a hardware fresh start, which is pretty interesting.

**Comment by eddievhfan1984** [comment]
Yeah, I noticed that. Maybe because recovering the counter from NEG_MAX would've taken too long, especially if you're running in AVERAGE G. Of course, weirdly enough, the CSM abort handler changes the P00DOO alarms to BAILOUT when AVERAGE G is running, but the LM abort handler doesn't.

It's especially annoying when you're in powered descent, the 1103 alarm is thrown, and you find that you can't get control of the computer back until you release the DAP. Then you can't even really manually abort, and re-selecting MODE CONTROL-AUTO throws the alarm again. ¯\(ツ)/¯

**Comment by rburkey2005** [comment]
Possibly the changes (see https://github.com/rburkey2005/virtualagc/issues/47) messed up the CMC in NASSP.  Reopening.

**Comment by indy91** [comment]
Should I use this for the problem discussion?

I have tracked down the cause of the standby and restart lights. Whenever a T6RUPT is triggered (output channel 13, bit 15) the DSKY processes channel 13 information. Channel 13 reads 37777 when I start a scenario with #47 implemented and it reads 40100 without the changes. So writing (almost) all ones to channel 13 causes the lights to be on.

**Comment by rburkey2005** [comment]
> Should I use this for the problem discussion?

Sure, why not?  As good a place as any.

**Comment by indy91** [comment]
Ok, it just was the decision between using #46 or #47 anyway.

I also think now it is causing problems for the LGC, too. Channel 13 is sometimes set to all ones, so 77777, during descent or ascent. This line in the agc_engine.c is writing something in the output channel:

`CpuWriteIO(State, 013, c(RegTIME6) & 037777);`

Could this somehow wrong? If it is something on the NASSP side of things, then it could be a wrong assumption about the the inversion of input/output channel bits or so. The output channel handling is done in the NASSP code, so it's certainly possible that the problem lies there.

**Comment by thewonderidiot** [comment]
Oh, whoops. That's a stupid mistake on my part. Should me masking out and writing the contents of channel 13, not of TIME6. One sec.

**Comment by indy91** [comment]
Thanks for this. I very much prefer stupid little mistakes to stupid big mistakes. This one was easily solved. I should have probably noticed it myself, but I tend to avoid lines of code with bitwise operators.

**Comment by rburkey2005** [comment]
It did sound odd. I was just resigning myself to having to look at it. Thank goodness!


Sent on my Virgin Mobile Samsung Galaxy S® 5

-------- Original message --------
