### ISSUE TITLE
Probably incorrect behavior of yaAGC Block II "editing registers"

### ISSUE THREAD

**Issue by rburkey2005** [rburkey2005/virtualagc#51]
Because of problems I've encountered writing the Block I AGC simulator, I _believe_ that the current behavior of the "editing registers" (`CYR`, `SR`, `CYL`, `SL`) is incorrect in yaAGC, and specifically incorrect in terms of trying to use them for multiple-precision shifting operations.

As currently implemented in yaAGC, they are logically 15-bit registers with the following behavior.  Assuming that you are trying to write the 15-bit pattern `D15 D14 .... D1` into them, you'd get:

- CYR: `D1 D15 D14 ... D2`
- SR: `D15 D15 D14 ... D2`
- CYL: `D14 ... D1 D15`
- SL: `D14 ... D1 0`

Notice, however, that this behavior would make them quite difficult to use for multiple-precision operations, because there's no way to propagate the bit that shifts out of a word into the word of the next higher or lower precision without a significant number of additional logical operations.

In Block I, these registers are explicitly 16-bit (see [table 3-2 on p. 3-3 of document R-393](http://www.ibiblio.org/apollo/hrst/archive/1008.pdf)), and if `SG D15 ... D1` is loaded into them, where `SG` is the sign bit (in the `A` register it would be bit 16) they'd behave like this:

- CYR: `D1 X SG D14 D13 ... D2`
- SR: `SG X SG D14 D13 ... D2`
- CYL: `D14 X D13 ... D1 SG`
- SL: `SG X D13 ... D1 SG`

where `X`="don't care".  In other words, `D15` plays no role, either in writing to the register or reading from it, and the physical `SG` bit logically acts something like `D15`.  _Moreover,_ because the `SG` bit in the `A` register is treated differently from other bits (in that it participates in conveying overflow information), there is the possibility of propagating it from one word to the next in a multi-precision shift operation.  

I think.  But I haven't quite worked out the details in Block 1 yet (in that I can't quite figure out where `SG` is actually coming from in every instruction, nor can I figure out yet what is _actually_ written to the `X` bit).  So I can't "fix" it in Block II until I first figure it out in Block I, which is proving to be a challenge.

Whether or not this is related to issue #50 or not, I don't know.

**Comment by rburkey2005** [comment]
Although the current behavior of yaAGC does correspond to [Figure 3 on p. 6 of AGC4 Memo #9](http://www.ibiblio.org/apollo/hrst/archive/1689.pdf).

Perhaps I was right the first time, and Block 2 is just that much different from Block 1?

**Comment by rburkey2005** [comment]
You know what?  I think this is wrong.  Never mind!

**Comment by thewonderidiot** [comment]
@rburkey2005, I think you were closer than you think you were. For Block 2, internally, when "bit 15" is used, it's actuall pulled from WL16/ rather than WL15/. The editing registers are no different; in actuality, bit 15 is completely discarded and bit 16 is the one that's copied around. Your X's above quite literally mean there's no connection for that operation to the G register, so during the clear time those bits will be reset to 0. Bit 16 is also the one that is written out to erasable memory, so the resulting overflow in G from, say, an SR, is fleeting and unimportant. 

I think they were probably exactly the same between Blocks 1 and 2. The difference is just in the level of detail of the reference material. The Block 1 table shows what goes into G, before it's written to memory, while the Block 2 table is more software centric and only looks at the end results in memory.

**Comment by rburkey2005** [comment]
I want to believe that.  I mean, I do believe you're right about Bit 15 
and Bit 16, and I've periodically toyed with swapping them ... but it 
never fixes my problem.  My problem is that in John Pultorak's 
simulator,  bit 16 of the editing registers can be set from time to 
time, in a pattern I can't identify but which is consistent.  So the 
extra bit /does/ get set (at least in the software simulation), but it's 
set from some lingering overflow or something, and I simply can't figure 
out where that "somewhere else" is. Which may not be important in any 
functional sense to Solarium, but makes a big difference to me in doing 
a cycle by cycle comparison of my simulator vs John's simulator.  I 
guess on your assurance, I can simply change John's simulator to always 
zero-out that bit.

**Comment by thewonderidiot** [comment]
Yeah, zeroing out that bit is what I would suggest -- I think, based on the fact that the data is going into G at all, that the editing register storage really is only 15 bits for Block 1, just like it is in Block 2. At least in Block 2, G is never used as temporary storage, and the editing registers are completely standard erasable memory locations. The editing happens during the write of the value to G. I would be very surprised at this point if there was some special physical flip-flop manifestation of them on Block 1.

**Comment by thewonderidiot** [comment]
And to be clear -- since the data is going out to erasable memory and back, bit 15 gets totally dropped, and then the one sign bit from erasable memory gets duplicated into bits 15 and 16 on read. So bit 16 can get set, in that sense.

**Comment by rburkey2005** [comment]
Turns out to be a big forehead slap. John's simulator is generating 
parity bits for everything, even those extra bits, and they were all 
showing up in the simulated registers.  I spent a couple of days trying 
to figure that out, before simply commenting out all the parity 
generation in his program.  D'oh!

**Comment by thewonderidiot** [comment]
Cool! Hooray for easy fixes.
