### ISSUE TITLE
Transcribe INPUT/OUTPUT CHANNELS (p.26)

### ISSUE THREAD

**Issue by thewonderidiot** [rburkey2005/virtualagc#64]
Transcribe the scans for the INPUT OUTPUT CHANNELS log section into [its source file](https://github.com/rburkey2005/virtualagc/blob/master/Aurora12/INPUT_OUTPUT_CHANNELS.agc). This section constitutes page 26.

[This section has a was eventually merged into Luminary 099's ERASABLE ASSIGNMENTS section](https://github.com/rburkey2005/virtualagc/blob/master/Luminary099/ERASABLE_ASSIGNMENTS.agc).
It's only 12 lines long, and most can probably be taken from the Luminary file.

Reduced quality scans can be found [here](http://www.ibiblio.org/apollo/ScansForConversion/Aurora12/). The original quality scans are available at [the Internet Archive page for Aurora](https://archive.org/details/aurora00dapg). Note that in both cases, the page numbers specified on this ticket are those printed on the original pages, *not* those in the filenames. The numbers will be close, though, so you should be able to find them pretty quickly. The start of the log section should be fairly obvious.

**Comment by thewonderidiot** [comment]
@jimlawton are you still planning on doing this?

**Comment by jimlawton** [comment]
Oops, sorry Mike, forgot I'd taken this one. I'll do it now.

**Comment by jimlawton** [comment]
Done and pushed. Sorry about that!

**Comment by thewonderidiot** [comment]
Haha, no worries! :)
