### ISSUE TITLE
Transcribe CONTROLLER AND METER ROUTINES (pp. 368-369)

### ISSUE THREAD

**Issue by thewonderidiot** [rburkey2005/virtualagc#83]
Transcribe the scans for the CONTROLLER AND METER ROUTINES log section into [its source file](https://github.com/rburkey2005/virtualagc/blob/master/Aurora12/CONTROLLER_AND_METER_ROUTINES.agc). This section ranges from pages 368 to 369.

This section has no corresponding log section in Luminary 099. It will have to be written from scratch.

Reduced quality scans can be found [here](http://www.ibiblio.org/apollo/ScansForConversion/Aurora12/). The original quality scans are available at [the Internet Archive page for Aurora](https://archive.org/details/aurora00dapg). Note that in both cases, the page numbers specified on this ticket are those printed on the original pages, *not* those in the filenames. The numbers will be close, though, so you should be able to find them pretty quickly. The start of the log section should be fairly obvious.

**Comment by nadalle** [comment]
I'm doing this one.

**Comment by thewonderidiot** [comment]
Thanks @nadelle!
