### ISSUE TITLE
Transcribe KALMAN FILTER FOR LEM DAP (pp. 604-614)

### ISSUE THREAD

**Issue by thewonderidiot** [rburkey2005/virtualagc#98]
Transcribe the scans for the KALMAN FILTER FOR LEM DAP log section into [its source file](https://github.com/rburkey2005/virtualagc/blob/master/Aurora12/KALMAN_FILTER_FOR_LEM_DAP.agc). This section ranges from pages 604 to 614.

[This section has a corresponding log section in Luminary 099](https://github.com/rburkey2005/virtualagc/blob/master/Luminary099/KALMAN_FILTER.agc). However, it appears, there is very little code overlap between the two. Most of this section will need to be written from scratch.

Reduced quality scans can be found [here](http://www.ibiblio.org/apollo/ScansForConversion/Aurora12/). The original quality scans are available at [the Internet Archive page for Aurora](https://archive.org/details/aurora00dapg). Note that in both cases, the page numbers specified on this ticket are those printed on the original pages, *not* those in the filenames. The numbers will be close, though, so you should be able to find them pretty quickly. The start of the log section should be fairly obvious.

**Comment by ohommes** [comment]
Finished transcription.
